python train/main.py train \
    --datadir data \
    --modeltype dncnn \
    --modeldir result/dncnn_spure_0/dncnn_spure_0.pth \
    --logdir result/dncnn_spure_0 \
    --numlayers 17 \
    --sigma 25 \
    --alpha 0.01 \
    --loss spure \
    --learnrate 1e-3 \
    --epochs 15 \
    --logevery 50
