python train/main.py train \
    --datadir data \
    --modeltype remez \
    --modeldir result/remez_pure_0/remez_pure_0.pth \
    --logdir result/remez_pure_0 \
    --numlayers 20 \
    --sigma 0 \
    --alpha 0.01 \
    --loss pure \
    --learnrate 1e-3 \
    --epochs 15 \
    --logevery 50
