python train/main.py train \
    --datadir data \
    --modeltype remez \
    --modeldir result/remez_mse_0/remez_mse_0.pth \
    --logdir result/remez_mse_0 \
    --numlayers 20 \
    --sigma 25 \
    --alpha 0.01 \
    --loss mse \
    --learnrate 1e-3 \
    --epochs 20 \
    --logevery 50
